export const enum YAPIX {
  BASE64_FILE_FLAG = '__YAPIX_BASE64_FILE__',
  HTTP_HEADERS_KEY = 'x-yapix-http-headers',
  HTTP_REQUEST_LISTENER_TYPE = '__YAPIX_HTTP_REQUEST_LISTENER__',
  HTTP_RESPONSE_LISTENER_TYPE = '__YAPIX_HTTP_RESPONSE_LISTENER__',
  BACKGROUND_HTTP_REQUEST_TYPE = '__YAPIX_BACKGROUND_HTTP_REQUEST__',
  FILE_BODY_KEY = '__YAPIX_FILE_BODY__',
  FILE_FIELD_FLAG = '__YAPIX_FILE_FIELD__',
}
